### ISSUE TITLE
February 30 ,31 exists

### ISSUE THREAD

**Issue by nam8u** [MozillaTN/Weeks-Of-Contirbution#36]
contact us page on date we can select date as feb 30 or 31

**Comment by vaidhyesh1** [comment]
I tried selecting feb 30 and feb31 but the drop down menu for date automatically changed the date to feb 29.check the url out: http://mozillatn.github.io/Weeks-Of-Contirbution/contact-us.html

**Comment by MozillaTN** [comment]
@drunkskunk and @nam8u we have used Google forms here instead of our own code, so what the form gives we are showing. So feeling this bug is invalid and closing it.
